import Head from "next/head";
import Footer from "../Components/Footer";

import Menu from "../Components/Menu";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://motos.org">Motos.js!</a>
        </h1>
      </main>

      <Footer />
    </div>
  );
}
